package com.example.testappforclicklead.model.constant

const val STATUS_INSTALLATION = "STATUS_INSTALLATION"
const val COUNT_START_APPLICATION = "COUNT_START_APPLICATION"
const val LAST_URL_IN_WEB = "LAST_URL_IN_WEB"
const val MAIN_URL_IN_WEB = "MAIN_URL_IN_WEB"

const val APPSFLYER = "APPSFLYER"
const val DEEPLINK_FACEBOOK = "DEEPLINK_FACEBOOK"

const val MAIN_ATTRIBUTE = "MAIN_ATTRIBUTE"

const val ORGANIC_INSTALL = "ORGANIC_INSTALL"
const val NOT_ORGANIC_INSTALL = "NOT_ORGANIC_INSTALL"
